### PR TITLE
Upgrade server side to JHipster 6.x for custom jhipster auditing

### PR DESCRIPTION
**Pull request by loverto**

### CODE REVIEW

**Comment by deepu105** [comment]
@hipster-labs/developers does anyone have bandwith to check this

**Comment by murdos** [comment]
> 
> 
> @hipster-labs/developers does anyone have bandwith to check this

I can test this PR if needed. 
But I'm more worried by the work needed for fixing integration tests on this project.
BTW it would be nice if you could give merge privileges on this project and/or organization too.

**Comment by deepu105** [comment]
Sure will do that

**Comment by murdos** [comment]
LGTM. At least this fixes the server side (and thus is useful for microservice).

The client side is however broken: wrong route/URL for accessing the entity-audit page from admin menu (`/entity-audit` vs `/admin/entity-audit`). Then content is not loaded in the table once you select the entity and load the changes.

**Comment by murdos** [comment]
Just forgot to say: there's still one issue server side when using `dev` profile and when fake data is enabled, as described in https://github.com/jhipster/generator-jhipster/issues/9804. I will fix it once a solution is provided on generator-jhipster.

**Comment by ChouSsu** [comment]
@murdos I'm also working on an upgrade for this module since a few weeks - didn't recognize this one - sorry - hence my work on ng-jhipster as well as generator-jhipster lately.
Perhaps you can have a look on my current state of work an give some adivse on how to proceed to not 'invent the wheel' twice ;).

https://github.com/ChouSsu/generator-jhipster-entity-audit/tree/jhipster6-compatibility

**Comment by murdos** [comment]
@ChouSsu Nice! Let's coordinate then in order to fix this module 😉
I was planning to work on fixing the fake data issue, but I see you've already started work, so I'll let you finish.

I think it would be better if you could split your work in different PR, rather than submit one big PR at end: I see that e.g. that you're removing support for AngularJs (I agree with that, but we need @deepu105 input on the matter) while fixing the Angular 2+ support.

And I think open PR that fixes the server side should be accepted and merged.

**Pull request merged**
