### PR TITLE
Compatible with projects generated after 3.6.0 with DTOs moved to service folder

### PR DESCRIPTION
**Pull request by leopku**
Otherwise, DTO files were still checked & generated under `web/rest/dto` folder

### CODE REVIEW

**Comment by cbornet** [comment]
The minimum jhipster version should probably be updated in package.json

**Comment by leopku** [comment]
Hi @cbornet,
I had updated `generator-jhipster` dependency from 3.0.0 to 3.6.0 in package.json.
Is there anything else I missed?

Regards.

**Comment by deepu105** [comment]
LGTM. I guess it would be too much to support multiple JHipster versions. People who would want to use this with older JH version can do so by installing [v2.1.0](https://github.com/hipster-labs/generator-jhipster-entity-audit/releases/tag/v2.1.0 ) or below

**Comment by cbornet** [comment]
We could just verify that the project jh version is ok and exit with instructions if not.

**Comment by deepu105** [comment]
I think we can, ill add that


Thanks & Regards,
Deepu

On Mon, Aug 29, 2016 at 4:06 PM, Christophe Bornet <notifications@github.com

**Pull request merged**
