### PR TITLE
Rewrite integration tests

### PR DESCRIPTION
**Pull request by murdos**
Remove former integration tests, and switched to a simpler setup using Github Actions

### CODE REVIEW

**Comment by deepu105** [comment]
Awesome man. Hey btw would you like to take over maintenance of this module?

**Comment by murdos** [comment]
@deepu105 : I'd be happy to help maintain this module. I'm not sure to have time to add new feature (like support for react and vuejs), but my plan is to make it work again with current JHipster, update dependencies and do some cleanup 😉

**Comment by murdos** [comment]
Merging even if tests are not green, because there are still compatibility issues with current JHipster. However these new tests will already be more helpful than previous ones

**Comment by poolebu** [comment]
Thank you @murdos for your work!! What compatibility issues?

**Comment by deepu105** [comment]
Thank you guys

Thanks & Regards,
Deepu

**Pull request merged**
