### PR TITLE
Updated the module to work with JHipster 6.x

### PR DESCRIPTION
**Pull request by yakari**
Updated the module to work with JHipster 6.x (tested with JHipster 6.4.1)

### CODE REVIEW

**Comment by deepu105** [comment]
@yakari thank you so much. We need to check why the build is failing

**Comment by deepu105** [comment]
@murdos would you be able to take a look

**Comment by yakari** [comment]
@deepu105 you're welcome, I actually had a need for this module to work with JHipster 6 :)

**Comment by poolebu** [comment]
Is there a way I can use this @yakari ? thank you

**Comment by murdos** [comment]
Thanks @yakari !
BTW there are still some compatibility issues with current JHipster. I'll try to work on the java backend, if you want to help, e.g. on the frontend part, you're welcome 😀
I've changed the integration tests, it should now be easier to detect issues with CI

**Comment by murdos** [comment]
@yakari : looks like you already did nearly all the job, in fact I was not testing with your changes (I messed up with branches tracking).
With https://github.com/hipster-labs/generator-jhipster-entity-audit/pull/126 the CI is now passing again 😀

**Pull request merged**
