### PR TITLE
Added instructions to use it with microservices

### PR DESCRIPTION
**Pull request by marcelinobadin**
I have added a section to instruct how to use it with the jhipster microservice architecture

### CODE REVIEW

**Comment by deepu105** [comment]
Thanks let me see if this can be automated based on the applicationType property so that we can simplify the instructions and ask people to run the module on both gateway and the service and let the module do whats required based on appType

**Comment by marcelinobadin** [comment]
Perfect, I think with the steps described it will help you to automate

**Comment by deepu105** [comment]
Yes but I will not have time utill next week so in the meantime if you want
to do it please do and will appreciate that.


Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
I have problem with this, the isntruction wiull work only when you have one gateway and one microservice, when you have multiple microservice you would have to somehow find a way to show all of them in a single gateway

**Comment by DanielFran** [comment]
Closing, since we migrate to a new blueprint version.
If you found any issue with latest version, please open a new issue.

**Pull request closed without merging**
